/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    BreathingExercise: typeof import('./src/components/BreathingExercise.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubTitle: typeof import('./src/components/SubTitle.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
